import { hashSync } from "bcrypt-ts-edge";
const sampleData = {
  users: [
    {
      name: "Waseem",
      email: "waseemkashif7@gmail.com",
      password: hashSync("12345678", 10),
      role: "admin",
    },
    {
      name: "aqif",
      email: "waseemqulandar@gmail.com",
      password: hashSync("12341234", 10),
      role: "user",
    },
  ],
  banners: [
    {
      webImage: "/images/desktop-banner.jpg",
      mobImage: "/images/mobile-banner.jpg",
      alt: "online exclusive",
    },
    {
      webImage: "/images/weekend-offers-web-en.jpg",
      mobImage: "/images/weekend-offers-mob-en.jpg",
      alt: "weekend offers",
    },
  ],
  categories: [
    {
      name: "Grocery",
      urlKey: "Groceries",
      icon: "/images/categories/grocery.png",
      title: "Grocery Shopping",
      description:
        " Buy grocery online in Qatar at best price for the convenience of express order delivery with www.ansargallery.com . Explore the variety from cooking, baking to fresh produce and dairy products in our online grocery shopping store. ✓ Express Delivery of Orders ✓ COD ✓ Card Payment. Shop grocery now",
    },
    {
      name: "Mobile-Phones",
      urlKey: "Mobile-Phones",
      icon: "/images/categories/mobile-phone.png",
      title: "Mobile Phone Shopping",
      description:
        " Buy Mobile-Phones online in Qatar at best price for the convenience of express order delivery with www.ansargallery.com . Explore the variety from cooking, baking to fresh produce and dairy products in our online grocery shopping store. ✓ Express Delivery of Orders ✓ COD ✓ Card Payment. Shop grocery now",
    },
    {
      name: "Electronics",
      urlKey: "electronics",
      icon: "/images/categories/Electronics.png",
      title: "electronics Shopping",
      description:
        " Buy electronics online in Qatar at best price for the convenience of express order delivery with www.ansargallery.com . Explore the variety from cooking, baking to fresh produce and dairy products in our online grocery shopping store. ✓ Express Delivery of Orders ✓ COD ✓ Card Payment. Shop grocery now",
    },
    {
      name: "Beauty & Care",
      urlKey: "beauty_care",
      icon: "/images/categories/beauty_care.png",
      title: "beauty_care Shopping",
      description:
        " Buy Beauty and Care online in Qatar at best price for the convenience of express order delivery with www.ansargallery.com . Explore the variety from cooking, baking to fresh produce and dairy products in our online grocery shopping store. ✓ Express Delivery of Orders ✓ COD ✓ Card Payment. Shop grocery now",
    },
    {
      name: "Household",
      urlKey: "household",
      icon: "/images/categories/houseHold.png",
      title: "beauty_care Shopping",
      description:
        " Buy household online in Qatar at best price for the convenience of express order delivery with www.ansargallery.com . Explore the variety from cooking, baking to fresh produce and dairy products in our online grocery shopping store. ✓ Express Delivery of Orders ✓ COD ✓ Card Payment. Shop grocery now",
    },
    {
      name: "Fashion",
      urlKey: "fashion",
      icon: "/images/categories/fashion.png",
      title: "beauty_care Shopping",
      description:
        " Buy fashion online in Qatar at best price for the convenience of express order delivery with www.ansargallery.com . Explore the variety from cooking, baking to fresh produce and dairy products in our online grocery shopping store. ✓ Express Delivery of Orders ✓ COD ✓ Card Payment. Shop grocery now",
    },
    {
      name: "Baby infants",
      urlKey: "baby_infants",
      icon: "/images/categories/babyInfants.png",
      title: "beauty_care Shopping",
      description:
        " Buy baby infants online in Qatar at best price for the convenience of express order delivery with www.ansargallery.com . Explore the variety from cooking, baking to fresh produce and dairy products in our online grocery shopping store. ✓ Express Delivery of Orders ✓ COD ✓ Card Payment. Shop grocery now",
    },
    {
      name: "Sports and Outdoor",
      urlKey: "sports_outdoor",
      icon: "/images/categories/sports_outdoor.png",
      title: "sports goods Shopping",
      description:
        " Buy sports and Outdoor online in Qatar at best price for the convenience of express order delivery with www.ansargallery.com . Explore the variety from cooking, baking to fresh produce and dairy products in our online grocery shopping store. ✓ Express Delivery of Orders ✓ COD ✓ Card Payment. Shop grocery now",
    },
    {
      name: "Furniture",
      urlKey: "furniture",
      icon: "/images/categories/furniture.png",
      title: "beauty_care Shopping",
      description:
        " Buy furniture online in Qatar at best price for the convenience of express order delivery with www.ansargallery.com . Explore the variety from cooking, baking to fresh produce and dairy products in our online grocery shopping store. ✓ Express Delivery of Orders ✓ COD ✓ Card Payment. Shop grocery now",
    },
  ],
  products: [
    {
      name: "Polo Sporting Stretch Shirt",
      slug: "polo-sporting-stretch-shirt",
      category: "fashion",
      description: "Classic Polo style with modern comfort",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
      ],
      regularPrice: "10",
      brand: "Polo",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "Brooks Brothers Long Sleeved Shirt new text to see the overflow effect",
      slug: "brooks-brothers-long-sleeved-shirt",
      category: "fashion",
      description: "Timeless style and premium comfort",
      images: [
        "/images/sample-products/p2-1.jpg",
        "/images/sample-products/p2-2.jpg",
      ],
      regularPrice: "10.50",
      discountedPrice: "8.50",
      brand: "Brooks Brothers",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "Tommy Hilfiger Classic Fit Dress Shirt",
      slug: "tommy-hilfiger-classic-fit-dress-shirt",
      category: "Men's Dress Shirts",
      description: "A perfect blend of sophistication and comfort",
      images: [
        "/images/sample-products/p3-1.jpg",
        "/images/sample-products/p3-2.jpg",
      ],
      regularPrice: "12.25",
      brand: "Tommy Hilfiger",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Calvin Klein Slim Fit Stretch Shirt",
      slug: "calvin-klein-slim-fit-stretch-shirt",
      category: "Men's Dress Shirts",
      description: "Streamlined design with flexible stretch fabric",
      images: [
        "/images/sample-products/p4-1.jpg",
        "/images/sample-products/p4-2.jpg",
      ],
      regularPrice: "55.75",
      discountedPrice: "49.75",
      brand: "Calvin Klein",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Classic Pink Hoodie",
      slug: "polo-classic-pink-hoodie",
      category: "Men's Sweatshirts",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
      ],
      regularPrice: "99.75",
      brand: "Polo",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Polo Ralph Lauren Oxford Shirt",
      slug: "polo-ralph-lauren-oxford-shirt",
      category: "Men's Dress Shirts",
      description: "Iconic Polo design with refined oxford fabric",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.jpg",
      ],
      regularPrice: "10",
      brand: "Polo",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Iphone 16 pro max (8GB RAM, 256GB)",
      slug: "iphone-16-pro-max",
      category: "Mobile-Phones",
      description: "Latest iPhone with advanced features",
      images: ["/images/sample-products/iphone16promax.jpg"],
      regularPrice: "4199.00",
      brand: "apple",
      rating: 4.7,
      numReviews: 12,
      stock: 2,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Apple Iphone 13 (4GB RAM, 256GB)",
      slug: "apple-iphone-13",
      category: "Mobile-Phones",
      description: "Latest iPhone with advanced features and great camera",
      images: ["/images/sample-products/iphone13.jpg"],
      regularPrice: "1699.00",
      brand: "apple",
      rating: 3.7,
      numReviews: 12,
      stock: 5,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Apple Watch Series 7",
      slug: "apple-watch-series-7",
      category: "apple smart watches",
      description: "Latest Apple Watch with advanced health features",
      images: ["/images/sample-products/appleWatch.jpg"],
      regularPrice: "4299.00",
      brand: "apple",
      rating: 4.7,
      numReviews: 12,
      stock: 2,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Apple Macbook Pro 2017",
      slug: "apple-macbook-pro",
      category: "macbooks",
      description: "Latest Apple macbook with advanced health features",
      images: ["/images/sample-products/macbookPro.jpg"],
      regularPrice: "8199.00",
      brand: "apple",
      rating: 4.7,
      numReviews: 0,
      stock: 1,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
